pipeline:
  name: github-repository
  identifier: githubrepository
  projectIdentifier: Test
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Deploy-to-k8s
        identifier: Deploytok8s
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: Githubk8sservice
          environment:
            environmentRef: k8smaster2
            deployToAll: false
            infrastructureDefinitions:
              - identifier: k8smaster2
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
